### ISSUE TITLE
[9292]Dutch Public Transit module

### ISSUE THREAD

**Issue by tyrope** [sopel-irc/sopel-extras#23]
Feature request from #YourPants-nl by lili

[API specs](https://github.com/timvanelsloo/9292-api-spec)

**Comment by dgw** [comment]
I suspect this is no longer wanted. If it is, and nobody has done so already… frankly, the best thing to do is make a module based off the [cookiecutter template](https://github.com/sopel-irc/sopel-cookiecutter) and publish it yourself. (We're trying to avoid adding any new modules to extras.)
