### ISSUE TITLE
Extra modules do not work...

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel-extras#64]
Hello.

Welcome to Willie. Loading modules...

Error loading twit: No module named tweepy (../../../../../../home/ant/.willie/modules/twit.py:10)
Error in helpbot setup procedure: 'Config' object has no attribute 'helpbot' (config/**init**.py:203)
Error loading dicelog: cannot import name calculate (../../../../../../home/ant/.willie/modules/dicelog.py:15)
Error in ai setup procedure: 'Config' object has no attribute 'ai' (config/**init**.py:203)
Setting up Bucket...
Error connecting to the bucket database.
Error in bucket setup procedure: 'Config' object has no attribute 'bucket' (config/**init**.py:203)
Error in document setup procedure: 'Config' object has no attribute 'document' (config/**init**.py:203)
Error in redmine setup procedure: 'Config' object has no attribute 'redmine' (config/**init**.py:203)
Error in imgur setup procedure: 'Config' object has no attribute 'imgur' (config/**init**.py:203)

Registered 55 modules,
8 modules failed to load

Connecting to [deleted]:6697...

I couldn't find all their packages, but tweepy failed:
$ sudo pip install tweepy
Downloading/unpacking tweepy
  Downloading tweepy-3.3.0.tar.gz
  Running setup.py egg_info for package tweepy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/ant/.willie/build/tweepy/setup.py", line 17, in <module>
        install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/ant/.willie/build/tweepy/setup.py", line 17, in <module>

```
install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())
```

TypeError: parse_requirements() got an unexpected keyword argument 'session'

---

Command python setup.py egg_info failed with error code 1 in /home/ant/.willie/build/tweepy
Storing complete log in /root/.pip/pip.log

ls modules/ -all
total 288
drwxr-xr-x 3 ant  ant   4096 Feb 20 01:09 .
drwxr-xr-x 5 ant  ant   4096 Feb 23 19:18 ..
-rw-r--r-- 1 ant  ant    786 Feb 20 00:49 8ball.py
-rw-r--r-- 1 ant  ant   1205 Feb 20 00:53 8ball.pyc
-rw-r--r-- 1 ant  ant   4987 Feb 20 00:48 ai.py
-rw-r--r-- 1 ant  ant   7481 Feb 20 00:53 ai.pyc
-rw-r--r-- 1 ant  ant   3592 Feb 20 00:48 bomb.py
-rw-r--r-- 1 ant  ant   3786 Feb 20 00:53 bomb.pyc
-rw-r--r-- 1 ant  ant  34290 Feb 20 00:48 bucket.py
-rw-r--r-- 1 ant  ant  30976 Feb 20 00:53 bucket.pyc
drwxr-xr-x 2 root root  4096 Feb 20 01:09 build
-rw-r--r-- 1 ant  ant   1473 Feb 20 00:47 debug.py
-rw-r--r-- 1 ant  ant   2112 Feb 20 00:53 debug.pyc
-rw-r--r-- 1 ant  ant   7356 Feb 20 00:47 dicelog.py
-rw-r--r-- 1 ant  ant   6536 Feb 20 00:53 dicelog.pyc
-rw-r--r-- 1 ant  ant   2968 Feb 20 00:47 document.py
-rw-r--r-- 1 ant  ant   3225 Feb 20 00:53 document.pyc
-rw-r--r-- 1 ant  ant    881 Feb 20 00:47 fuckingweather.py
-rw-r--r-- 1 ant  ant   1277 Feb 20 00:53 fuckingweather.pyc
-rw-r--r-- 1 ant  ant   5920 Feb 20 00:47 helpbot.py
-rw-r--r-- 1 ant  ant   6780 Feb 20 00:53 helpbot.pyc
-rw-r--r-- 1 ant  ant  10546 Feb 20 00:46 imgur.py
-rw-r--r-- 1 ant  ant   9527 Feb 20 00:53 imgur.pyc
-rw-r--r-- 1 ant  ant    613 Feb 20 00:46 multimessage.py
-rw-r--r-- 1 ant  ant    963 Feb 20 00:53 multimessage.pyc
-rw-r--r-- 1 ant  ant   5341 Feb 20 00:46 nws.py
-rw-r--r-- 1 ant  ant   5424 Feb 20 00:53 nws.pyc
-rw-r--r-- 1 ant  ant   4031 Feb 20 00:46 oblique.py
-rw-r--r-- 1 ant  ant   4481 Feb 20 00:53 oblique.pyc
-rw-r--r-- 1 ant  ant   5104 Feb 20 00:46 redmine.py
-rw-r--r-- 1 ant  ant   5270 Feb 20 00:53 redmine.pyc
-rw-r--r-- 1 ant  ant   2725 Feb 20 00:46 roulette.py
-rw-r--r-- 1 ant  ant   2297 Feb 20 00:53 roulette.pyc
-rw-r--r-- 1 ant  ant   1069 Feb 20 00:46 slap.py
-rw-r--r-- 1 ant  ant   1384 Feb 20 00:53 slap.pyc
-rw-r--r-- 1 ant  ant   6900 Feb 20 00:47 twit.py
-rw-r--r-- 1 ant  ant   7075 Feb 20 00:53 twit.pyc
-rw-r--r-- 1 ant  ant   3020 Feb 20 00:47 whois.py
-rw-r--r-- 1 ant  ant   4527 Feb 20 00:53 whois.pyc

How can I use these 8 extra modules to work in v5.1.1 on my Debian stable? The original default modules are fine (0 failed).

Thank you in advance. :)

**Comment by firerogue** [comment]
According to your errors, you're simply missing configs for the extra
modules.
Now, I haven't looked at the codebase in a while so I could be mistaken,
but I think rerunning the config wizard with the extra modules installed
should let you configure them.
Alternatively, open the config file in a text editor and do it manually

**Comment by firerogue** [comment]
Additionally, twit is failing because it has tweepy as a dependency whice you haven't installed, and dicelog is failing because it relies on the calc module which has changed

**Comment by antdude** [comment]
How do I resolve my tweepy install issue then?

**Comment by matiasw** [comment]
> I think rerunning the config wizard with the extra modules installed should let you configure them
Just for anyone else wondering, the relevant command is `willie --configure-modules`.
