### ISSUE TITLE
Imgur module: Unicode related

### ISSUE THREAD

**Issue by matiasw** [sopel-irc/sopel-extras#74]
<code><pre>http://imgur.com/gallery/gxWX0v6
     willie_5.4.1 UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' 
              in position 66: ordinal not in range(128) (file 
              "/home/appas/.willie/modules/imgur.py", line 47, in resource)
</pre></code>

**Comment by dgw** [comment]
This is probably fixed by #77
